#!/system/bin/sh

MEDIA_PATH="/data/media/0"
INSTALL_PATH="/data/local"

while [ $(getprop sys.boot_completed) != "1" ]; do
    sleep 5
done

if [ -f $MEDIA_PATH/entware.tar ] && [ -f $MEDIA_PATH/gnutar ]; then
    rm -rf $INSTALL_PATH/entware
    mkdir -p $INSTALL_PATH/entware
    cd $INSTALL_PATH/entware
    chmod +x $MEDIA_PATH/gnutar
    $MEDIA_PATH/gnutar xpvf $MEDIA_PATH/entware.tar
    rm -rf $MEDIA_PATH/entware.tar
    rm -rf $MEDIA_PATH/gnutar
fi

[ ! -d $INSTALL_PATH/entware ] && exit 0

/system/bin/mount -o rw,remount /
/system/bin/mkdir /opt
/system/bin/mkdir /bin
ln -s /system/bin/sh /bin/sh
/system/bin/mount -o ro,remount /

/system/bin/mount -o bind $INSTALL_PATH/entware /opt

/system/bin/mount -o rw,remount /system
ln -s /opt/etc/resolv.conf /system/etc/resolv.conf
/system/bin/mount -o ro,remount /system

/opt/etc/init.d/rc.unslung start